workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_commit_request"
      when: never
    - when: always

stages:
  - test
  - build

unit_testing:
  image: node:16-alpine
  stage: test
  cache:
    paths:
      - app/modules
  script:
    - cd app
    - npm install
    - npm run test

image_build_push:
  image: docker:27.4.0-rc.2-cli
  services:
    - docker:27.4.0-rc.2-dind
  stage: build
  script:
    - apk add --no-cache jq httpie
    - export JSON_VERSION=$(cat app/package.json | jq -r .version)
    - export VERSION=$JSON_VERSION.$CI_PIPELINE_ID
    - echo $VERSION
    - echo "VERSION=$VERSION" >> environmental_variables.env
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$VERSION .
    - docker push $CI_REGISTRY_IMAGE:$VERSION
  artifacts:
    reports:
      dotenv: environmental_variables.env


container_deploying:
  image: docker:dind
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ec2-user@$EC2_LOGIN "
        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        touch testssh.txt"




